apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qa-fe
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qa-fe
    spec:
      containers:
        - image: scgskku/ice-gs-thesis-fe-cbt
          imagePullPolicy: Always
          name: fe
          ports:
            - containerPort: 3000
