apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-qa
namePrefix: qa-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/fe
images:
- name: scgskku/ice-gs-thesis-fe-cbt
  newTag: ba9968aee5e63e7e07921de2e8c1a6e7b37cf0ce
