apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-qa
namePrefix: qa-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/fe
images:
- name: registry.scg.skku.ac.kr/ice-gs-thesis-fe
  newTag: 9ab629e5358ec6e80c057248f13ba73056f624f1
