apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-qa
namePrefix: qa-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/fe
images:
- name: registry.scg.skku.ac.kr/ice-gs-thesis-fe
  newTag: 9b6c880691dc926360977c5a122082e2ba579615
