apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prod-be
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prod-be
    spec:
      containers:
        - image: registry.scg.skku.ac.kr/cs-grad-thesis-be
          imagePullPolicy: Always
          name: be
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: cs-grad-thesis-prod-config
