apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cs-grad-thesis
namePrefix: prod-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/be
images:
- name: registry.scg.skku.ac.kr/cs-grad-thesis-be
  newTag: prod0
