apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-prod
namePrefix: prod-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/be
- secret.yaml
images:
- name: jcy0308/ice-gs-thesis-be-prod
  newTag: eccce19d42210148ef165839c6813ff6616fd6a6
