apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-prod
namePrefix: prod-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/be
- secret.yaml
images:
- name: jcy0308/ice-gs-thesis-be-prod
  newTag: bf2ba86a0f3b4d034d8e3b1676be7a7aecb2d18a
