apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-qa
namePrefix: qa-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/be
- ingress-swagger.yaml
- secret.yaml
images:
- name: jcy0308/ice-gs-thesis-be-qa
  newTag: b0894b102a2c85499b8c506de24e14ac86b1152c
