apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-qa
namePrefix: qa-
patchesStrategicMerge:
  - ingress.yaml
  - deployment.yaml
  - service.yaml
resources:
  - ../../../base/be
  - ingress-swagger.yaml
images:
  - name: harbor.k8s.scg.skku.ac.kr/library/ice-gs-thesis-be
    newTag: qa1
