apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-qa
namePrefix: qa-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/be
- ingress-swagger.yaml
- secret.yaml
images:
- name: jcy0308/ice-gs-thesis-be-qa
  newTag: 9158320122bcc98a4674f4cb4719d275990aed77
