apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-prod
namePrefix: prod-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/fe
images:
- name: harbor.k8s.scg.skku.ac.kr/library/ice-gs-thesis-fe
  newTag: d59b30e84f4ad96459a57254d668ed2273422ed4
