apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ice-gs-thesis-prod
namePrefix: prod-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/fe
images:
- name: harbor.k8s.scg.skku.ac.kr/library/ice-gs-thesis-fe
  newTag: 8cb6142ba38c024f2a028f0899ef150bb29df4d6
