apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cs-grad-thesis
namePrefix: dev-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../../base/fe
images:
- name: registry.scg.skku.ac.kr/cs-grad-thesis-fe
  newTag: dev2
